spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=postgres
spring.datasource.password=t16a11

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=kjsdhfjkh398fklsdfkljwio7r8923uzxcbfjkh2iuryi2
jwt.expiration=3600000